server {
    listen 80;
    # ชี้ไปที่นี่ เพราะบน GitHub โฟลเดอร์ public อยู่ชั้นนอกสุดแล้ว
    root /var/www/html/sdv/vehicle-system/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 3. จัดการไฟล์ PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        # สำคัญมาก: ตัวแปรนี้ต้องชี้ไปที่ไฟล์ index.php จริงๆ
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}